on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          export $(cat .env | xargs)
          sudo apt update
          sudo apt install -y curl llvm-dev libclang-dev clang openjdk-8-jre
          curl -O https://archive.apache.org/dist/pulsar/pulsar-$PULSAR_VERSION/DEB/apache-pulsar-client.deb
          curl -O https://archive.apache.org/dist/pulsar/pulsar-$PULSAR_VERSION/DEB/apache-pulsar-client-dev.deb
          sudo apt install -y ./apache-pulsar-client.deb ./apache-pulsar-client-dev.deb
          rm -rf apache-pulsar-client.deb apache-pulsar-client-dev.deb
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          source $HOME/.cargo/env
          cargo build -vv
      - name: Test
        run: |
          export $(cat .env | xargs)
          source $HOME/.cargo/env
          curl -O http://mirror.nbtelecom.com.br/apache/pulsar/pulsar-$PULSAR_VERSION/apache-pulsar-$PULSAR_VERSION-bin.tar.gz
          tar -zxvf apache-pulsar-$PULSAR_VERSION-bin.tar.gz
          ./apache-pulsar-$PULSAR_VERSION/bin/pulsar standalone &
          sleep 60
          cargo test -vv -- --nocapture
